services:
  # Backend Service
  - type: web
    name: express-backend
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: DB_HOST
        value: csce-315-db.engr.tamu.edu
      - key: DB_USER
        value: gang_y4
      - key: DB_PASSWORD
        value: DnXcW8o1
      - key: DB_NAME
        value: gang_y4_db
      - key: DB_PORT
        value: 5432
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production

  # Frontend Service
  - type: web
    name: react-frontend
    env: node
    plan: free
    rootDir: client
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_API_URL
        value: https://express-backend-yvwj.onrender.com